#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Front_End.Resource", IsApplication=true)]

namespace Front_End
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int activitylog_colors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int blue = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int blue_hover = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int grey = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int light_grey = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int pale_blue = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int pale_green = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int pale_red = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int pale_yellow = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int planner_activitylog_font = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int planner_divider = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bluedown = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blueup = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int grey = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int red = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int reddown = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int redup = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int NewLastName = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int NewName = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int NewPassword = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int NewUserName = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int activity_id = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int activity_log_id = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int btnLogin = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int button2 = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int image2 = 2131230726;
			
			// aapt resource value: 0x7f08002a
			public const int llActivities = 2131230762;
			
			// aapt resource value: 0x7f080005
			public const int myButton = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int ratingBar1 = 2131230724;
			
			// aapt resource value: 0x7f080029
			public const int rlDropzone = 2131230761;
			
			// aapt resource value: 0x7f080010
			public const int rlTimeMarkers = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int svCalendar = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int tv0000 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int tv0100 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int tv0200 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int tv0300 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int tv0400 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int tv0500 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int tv0600 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int tv0700 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int tv0800 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int tv0900 = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int tv1000 = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int tv1100 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int tv1200 = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int tv1300 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int tv1400 = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int tv1500 = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int tv1600 = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int tv1700 = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int tv1800 = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int tv1900 = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int tv2000 = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int tv2100 = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int tv2200 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int tv2300 = 2131230760;
			
			// aapt resource value: 0x7f080002
			public const int tvActivityName = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int tvStartEndTimes = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int txtPassword = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int txtUsername = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityLogEvent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Layout1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int t0000hrs = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int t0100hrs = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int t0200hrs = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int t0300hrs = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int t0400hrs = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int t0500hrs = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int t0600hrs = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int t0700hrs = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int t0800hrs = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int t0900hrs = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int t1000hrs = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int t1100hrs = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int t1200hrs = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int t1300hrs = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int t1400hrs = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int t1500hrs = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int t1600hrs = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int t1700hrs = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int t1800hrs = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int t1900hrs = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int t2000hrs = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int t2100hrs = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int t2200hrs = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int t2300hrs = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int horizontal_divider = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
