#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Front_End.Resource", IsApplication=true)]

namespace Front_End
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bluedown = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blueup = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int grey = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int red = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int reddown = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int redup = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int btnLogin = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int image2 = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int llActivities = 2131034145;
			
			// aapt resource value: 0x7f050001
			public const int myButton = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ratingBar1 = 2131034112;
			
			// aapt resource value: 0x7f050020
			public const int rlDropzone = 2131034144;
			
			// aapt resource value: 0x7f050007
			public const int rlTimeMarkers = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int svCalendar = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int tv0000 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int tv0100 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int tv0200 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tv0300 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int tv0400 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int tv0500 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int tv0600 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int tv0700 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int tv0800 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int tv0900 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int tv1000 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int tv1100 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int tv1200 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int tv1300 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int tv1400 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int tv1500 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int tv1600 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int tv1700 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int tv1800 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int tv1900 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int tv2000 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int tv2100 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int tv2200 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int tv2300 = 2131034143;
			
			// aapt resource value: 0x7f050004
			public const int txtPassword = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int txtUsername = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int t0000hrs = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int t0100hrs = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int t0200hrs = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int t0300hrs = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int t0400hrs = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int t0500hrs = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int t0600hrs = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int t0700hrs = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int t0800hrs = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int t0900hrs = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int t1000hrs = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int t1100hrs = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int t1200hrs = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int t1300hrs = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int t1400hrs = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int t1500hrs = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int t1600hrs = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int t1700hrs = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int t1800hrs = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int t1900hrs = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int t2000hrs = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int t2100hrs = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int t2200hrs = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int t2300hrs = 2130968601;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
